# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d5f57b28e63c617830d151abd8e52ccaff5400a4fffc501aab09730ea6bebc32ad7648182a04cff01bef9451a870d22087dea8080df526b2f34417c4cfadf74

test:
  secret_key_base: be0879d3126035c81cf0b006da2551475c68da5c1522aec28b4489a2ad3b65ad91b2c8b94a9e3d3dc0021d94a9a09aa127e63ede0cb2dd8a8695de152c043f92

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
